import type { Metadata } from "next";
import "../globals.css";
import { Box } from "@mui/material";
import Sidebar from "@/components/Sidebar/Sidebar";
import TopBar from "@/components/Topbar/Topbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personal Monee Control",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen antialiased px-6 overflow-hidden`}
      >
        <AppRouterCacheProvider>
          <Box sx={{ height: "100%", display: "flex", gap: "32px" }}>
            <Sidebar />
            <Box sx={{ flexGrow: 1 }}>
              <TopBar />
              {children}
            </Box>
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
